### ISSUE TITLE
JaCoCo ends up in release

### ISSUE THREAD

**Issue by dmfrey** [android10/Android-CleanArchitecture#118]
The JaCoCo stuff is ending up in the release after:

```
    ./gradlew assembleRelease
```

It is causing a failure to load on am Amazon Fire TV.  Doesn't seem to affect phones/tablets or a Nexus Player.

```
Didn't find class "org.jacoco.agent.rt.internal_773e439.Offline" on
path: DexPathList[[zip file "/data/app/org.mythtv.android-1/base.apk

Regards,
Karl


W/ActivityManager(  466): Input dispatching paused for current
ActivityRecord: ActivityRecord{1b328d98 u0
org.mythtv.android/.presentation.view.activity.TvMainActivity t51}
V/WindowManager(  466): addAppToken: AppWindowToken{2ef599d6
token=Token{173ac9f1 ActivityRecord{1b328d98 u0
org.mythtv.android/.presentation.view.activity.TvMainActivity t51}}} to
stack=1 task=51 at 0
W/art     (  140): PreZygoteFork called when we already have a zygote space.
…

D/BatteryStatsExtension.VitalEmitterBatteryAndTime(  466):
VitalEmitterBatteryAndTime.start(-): not runnable
V/WindowManager(  466): Adding window Window{24cd9be5 u0 Starting
org.mythtv.android} at 12 of 14 (after Window{23c0b7b u0
com.amazon.tv.settings/com.amazon.tv.settings.tv.BuellerApplicationDetailSettingsActivity})
I/ActivityManager(  466): Start proc 2663:org.mythtv.android/u0a16 for
activity org.mythtv.android/.presentation.view.activity.TvMainActivity
D/ActivityManager( 2663): default service binder =
android.os.BinderProxy@34e131dd
D/ActivityManager( 2663): default service =
android.app.ActivityManagerProxy@f01c152
I/wpa_supplicant(  787): wlan0: CTRL-EVENT-SCAN-RESULTS
…

D/BatteryStatsExtension.VitalEmitterBatteryAndTime(  466):
VitalEmitterBatteryAndTime.start(-): not runnable
W/SurfaceFlinger(  118): couldn't log to binary event log: overflow.
I/Choreographer(  466): Skipped 30 frames!  The application may be doing
too much work on its main thread.
D/VendorDisplayManagerGlobalCallback( 2663): callGetInstance: nil
I/PointerController(  466): PointerController setInvisible
W/SchedPolicy(  466): Failed to set io priority for tid 2470 (No such
process)
W/SchedPolicy(  466): Failed to set io priority for tid 2471 (No such
process)
I/ContextImpl( 2663): com.amazon.client.metrics.api registered service
at i = 71
D/ProfileManager( 2663): Create ProfileManager instance
D/AndroidRuntime( 2663): Shutting down VM
E/AndroidRuntime( 2663): FATAL EXCEPTION: main
E/AndroidRuntime( 2663): Process: org.mythtv.android, PID: 2663
E/AndroidRuntime( 2663): java.lang.NoClassDefFoundError: Failed
resolution of: Lorg/jacoco/agent/rt/internal_773e439/Offline;
E/AndroidRuntime( 2663):        at
org.mythtv.android.data.executor.JobExecutor_Factory.$jacocoInit(JobExecutor_Factory.java)
E/AndroidRuntime( 2663):        at
org.mythtv.android.data.executor.JobExecutor_Factory.<clinit>(JobExecutor_Factory.java)
E/AndroidRuntime( 2663):        at
org.mythtv.android.data.executor.JobExecutor_Factory.create(JobExecutor_Factory.java)
E/AndroidRuntime( 2663):        at
org.mythtv.android.presentation.internal.di.components.DaggerApplicationComponent.initialize(DaggerApplicationComponent.java:113)
E/AndroidRuntime( 2663):        at
org.mythtv.android.presentation.internal.di.components.DaggerApplicationComponent.<init>(DaggerApplicationComponent.java:100)
E/AndroidRuntime( 2663):        at
org.mythtv.android.presentation.internal.di.components.DaggerApplicationComponent.<init>(DaggerApplicationComponent.java:68)
E/AndroidRuntime( 2663):        at
org.mythtv.android.presentation.internal.di.components.DaggerApplicationComponent$Builder.build(DaggerApplicationComponent.java:193)
E/AndroidRuntime( 2663):        at
org.mythtv.android.presentation.AndroidApplication.initializeInjector(AndroidApplication.java:30)
E/AndroidRuntime( 2663):        at
org.mythtv.android.presentation.AndroidApplication.onCreate(AndroidApplication.java:22)
E/AndroidRuntime( 2663):        at
android.app.Instrumentation.callApplicationOnCreate(Instrumentation.java:1015)
E/AndroidRuntime( 2663):        at
android.app.ActivityThread.handleBindApplication(ActivityThread.java:4753)
E/AndroidRuntime( 2663):        at
android.app.ActivityThread.access$1500(ActivityThread.java:160)
E/AndroidRuntime( 2663):        at
android.app.ActivityThread$H.handleMessage(ActivityThread.java:1381)
E/AndroidRuntime( 2663):        at
android.os.Handler.dispatchMessage(Handler.java:102)
E/AndroidRuntime( 2663):        at android.os.Looper.loop(Looper.java:135)
E/AndroidRuntime( 2663):        at
android.app.ActivityThread.main(ActivityThread.java:5462)
E/AndroidRuntime( 2663):        at java.lang.reflect.Method.invoke(Native Method)
E/AndroidRuntime( 2663):        at
java.lang.reflect.Method.invoke(Method.java:372)
E/AndroidRuntime( 2663):        at
com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:964)
E/AndroidRuntime( 2663):        at
com.android.internal.os.ZygoteInit.main(ZygoteInit.java:759)
E/AndroidRuntime( 2663): Caused by: java.lang.ClassNotFoundException:
…

Didn't find class "org.jacoco.agent.rt.internal_773e439.Offline" on
path: DexPathList[[zip file "/data/app/org.mythtv.android-1/base.apk",
…
```

**Comment by Trikke** [comment]
I don't see how this has anything to do with this project? Did you meant to post this some where else?

**Comment by dmfrey** [comment]
No, I am using this project as guideline for my project. Are you
experiencing the same issue?

**Comment by Trikke** [comment]
No, of course not. This example project doesn't use "JaCoCo". In your stack trace there is also nothing that refers to this project.

**Comment by android10** [comment]
@Trikke :+1: . 
@dmfrey closing this issue since it has nothing to do with the project.

**Comment by dmfrey** [comment]
No worries. It was my issue. Forgot to close it.
