### ISSUE TITLE
java.lang.VerifyError: com/fernandocejas/android10/sample/data/net/RestApiImpl$AjcClosure1

### ISSUE THREAD

**Issue by FutureHere** [android10/Android-CleanArchitecture#173]
start demo in androidstudio  then crashed .it happens everytime, here the logcat:

  java.lang.VerifyError: com/fernandocejas/android10/sample/data/net/RestApiImpl$AjcClosure1
                                                                                                         at com.fernandocejas.android10.sample.data.net.RestApiImpl.userEntityList(RestApiImpl.java:53)
                                                                                                         at com.fernandocejas.android10.sample.data.repository.datasource.CloudUserDataStore.userEntityList(CloudUserDataStore.java:51)
                                                                                                         at com.fernandocejas.android10.sample.data.repository.UserDataRepository.users(UserDataRepository.java:54)
                                                                                                         at com.fernandocejas.android10.sample.domain.interactor.GetUserList.buildUseCaseObservable(GetUserList.java:41)
                                                                                                         at com.fernandocejas.android10.sample.domain.interactor.UseCase.execute(UseCase.java:60)
                                                                                                         at com.fernandocejas.android10.sample.presentation.presenter.UserListPresenter.getUserList(UserListPresenter.java:115)
                                                                                                         at com.fernandocejas.android10.sample.presentation.presenter.UserListPresenter.loadUserList(UserListPresenter.java:79)
                                                                                                         at com.fernandocejas.android10.sample.presentation.presenter.UserListPresenter.initialize(UserListPresenter.java:70)
                                                                                                         at com.fernandocejas.android10.sample.presentation.view.fragment.UserListFragment.loadUserList(UserListFragment.java:158)
                                                                                                         at com.fernandocejas.android10.sample.presentation.view.fragment.UserListFragment.onViewCreated(UserListFragment.java:80)

can you give some help?

**Comment by android10** [comment]
It is not happening to me. And try if you can build and execute from the command line. Otherwise it might be your setup/android studio.

Or if you give more context I will reopen this issue.

**Comment by filatoff** [comment]
Dupicate https://github.com/android10/Android-CleanArchitecture/issues/142
