### ISSUE TITLE
java.lang.VerifyError  ， help..

### ISSUE THREAD

**Issue by yuxinLi** [android10/Android-CleanArchitecture#180]
FATAL EXCEPTION: main
                                                                                                   Process: com.fernanependocejas.android10.sample.presentation, PID: 8344
                                                                                                   java.lang.VerifyError: com/fernandocejas/android10/sample/data/net/RestApiImpl$AjcClosure1
                                                                                                       at com.fernandocejas.android10.sample.data.net.RestApiImpl.userEntityList(RestApiImpl.java:53)
                                                                                                       at com.fernandocejas.android10.sample.data.repository.datasource.CloudUserDataStore.userEntityList(CloudUserDataStore.java:51)
                                                                                                       at com.fernandocejas.android10.sample.data.repository.UserDataRepository.users(UserDataRepository.java:53)
                                                                                                       at com.fernandocejas.android10.sample.domain.interactor.GetUserList.buildUseCaseObservable(GetUserList.java:41)
                                                                                                       at com.fernandocejas.android10.sample.domain.interactor.UseCase.execute(UseCase.java:60)
                                                                                                       at com.fernandocejas.android10.sample.presentation.presenter.UserListPresenter.getUserList(UserListPresenter.java:115)
                                                                                                       at com.fernandocejas.android10.sample.presentation.presenter.UserListPresenter.loadUserList(UserListPresenter.java:79)
                                                                                                       at com.fernandocejas.android10.sample.presentation.presenter.UserListPresenter.initialize(UserListPresenter.java:70)
                                                                                                       at com.fernandocejas.android10.sample.presentation.view.fragment.UserListFragment.loadUserList(UserListFragment.java:158)
                                                                                                       at com.fernandocejas.android10.sample.presentation.view.fragment.UserListFragment.onViewCreated(UserListFragment.java:80)
                                                                                                       at android.app.FragmentManagerImpl.moveToState(FragmentManager.java:910)
                                                                                                       at android.app.FragmentManagerImpl.moveToState(FragmentManager.java:1071)
                                                                                                       at android.app.BackStackRecord.run(BackStackRecord.java:684)
                                                                                                       at android.app.FragmentManagerImpl.execPendingActions(FragmentManager.java:1456)
                                                                                                       at android.app.Activity.performStart(Activity.java:5295)
                                                                                                       at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2268)
                                                                                                       at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2345)
                                                                                                       at android.app.ActivityThread.access$1100(ActivityThread.java:139)
                                                                                                       at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1256)
                                                                                                       at android.os.Handler.dispatchMessage(Handler.java:102)
                                                                                                       at android.os.Looper.loop(Looper.java:136)
                                                                                                       at android.app.ActivityThread.main(ActivityThread.java:5314)
                                                                                                       at java.lang.reflect.Method.invokeNative(Native Method)
                                                                                                       at java.lang.reflect.Method.invoke(Method.java:515)
                                                                                                       at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:864)
                                                                                                       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:680)
                                                                                                       at dalvik.system.NativeStart.main(Native Method)

**Comment by filatoff** [comment]
Dupicate #142
