### ISSUE TITLE
NullPointerException on UserListActivity

### ISSUE THREAD

**Issue by Drake1804** [android10/Android-CleanArchitecture#92]
Had crash on first launch. After i clicked on load sample data. 
`12-23 12:46:53.522 2958-2958/com.fernanependocejas.android10.sample.presentation E: FATAL EXCEPTION: main
                                                                                    Process: com.fernanependocejas.android10.sample.presentation, PID: 2958
                                                                                    java.lang.RuntimeException: Unable to start activity ComponentInfo{com.fernanependocejas.android10.sample.presentation/com.fernandocejas.android10.sample.presentation.view.activity.UserListActivity}: java.lang.NullPointerException
                                                                                        at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2184)
                                                                                        at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2233)
                                                                                        at android.app.ActivityThread.access$800(ActivityThread.java:135)
                                                                                        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1196)
                                                                                        at android.os.Handler.dispatchMessage(Handler.java:102)
                                                                                        at android.os.Looper.loop(Looper.java:136)
                                                                                        at android.app.ActivityThread.main(ActivityThread.java:5001)
                                                                                        at java.lang.reflect.Method.invokeNative(Native Method)
                                                                                        at java.lang.reflect.Method.invoke(Method.java:515)
                                                                                        at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:785)
                                                                                        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:601)
                                                                                        at dalvik.system.NativeStart.main(Native Method)
                                                                                     Caused by: java.lang.NullPointerException
                                                                                        at com.fernandocejas.frodo.aspect.LogObservable.methodAnnotatedWithRxLogObservable(LogObservable.java:27)
                                                                                        at com.fernandocejas.android10.sample.data.net.RestApiImpl.userEntityList(RestApiImpl.java)
                                                                                        at com.fernandocejas.android10.sample.data.repository.datasource.CloudUserDataStore.userEntityList(CloudUserDataStore.java:51)
                                                                                        at com.fernandocejas.android10.sample.data.repository.UserDataRepository.users(UserDataRepository.java:54)
                                                                                        at com.fernandocejas.android10.sample.domain.interactor.GetUserList.buildUseCaseObservable(GetUserList.java:41)
                                                                                        at com.fernandocejas.android10.sample.domain.interactor.UseCase.execute(UseCase.java:59)
                                                                                        at com.fernandocejas.android10.sample.presentation.presenter.UserListPresenter.getUserList(UserListPresenter.java:113)
                                                                                        at com.fernandocejas.android10.sample.presentation.presenter.UserListPresenter.loadUserList(UserListPresenter.java:77)
                                                                                        at com.fernandocejas.android10.sample.presentation.presenter.UserListPresenter.initialize(UserListPresenter.java:68)
                                                                                        at com.fernandocejas.android10.sample.presentation.view.fragment.UserListFragment.loadUserList(UserListFragment.java:155)
                                                                                        at com.fernandocejas.android10.sample.presentation.view.fragment.UserListFragment.onActivityCreated(UserListFragment.java:76)
`

**Comment by mpeng5120** [comment]
I also have the same problem, how to solve it

**Comment by android10** [comment]
Interesting. This has to do with https://github.com/android10/frodo library. Will look into it. In the meantime if you guys has problems, you can deactivate RxJava Debugging by just commenting a line and removing all frodo annotations:
https://github.com/android10/Android-CleanArchitecture/blob/master/data/build.gradle#L12

**Comment by androidShuang** [comment]
@Pointcut(METHOD)
  public static boolean methodAnnotatedWithRxLogObservable(ProceedingJoinPoint joinPoint) {
    final FrodoProceedingJoinPoint frodoJoinPoint = new FrodoProceedingJoinPoint(joinPoint);
    final Annotation annotation = frodoJoinPoint.getAnnotation(RxLogObservable.class);
    return ((MethodSignature) joinPoint.getSignature()).getReturnType() == Observable.class
        && ((RxLogObservable)annotation).value() != RxLogObservable.Scope.NOTHING;
  }

Caused by annotation is null but the frodoJoinPoint.getAnnotation(RxLogObservable.class) is not null

**Comment by android10** [comment]
@androidShuang @mpeng5120 @Drake1804 can you guys put the steps to reproduce it? I cannot reproduce it. It is working for me. Which RxJava version are you using?

**Comment by Kevin1466** [comment]
Yes, after commenting the line and removing all frodo annotations, it works. Thanks.

**Comment by android10** [comment]
This is solved here:
https://github.com/android10/Android-CleanArchitecture/commit/afd1481da9449d536a48806444f6f4d63109ce73

**Comment by nanbowan** [comment]
I still can't solved it

**Comment by spirosoik** [comment]
@nanbowan did you remove the ```@RxLogSubscriber``` annotation?

**Comment by nanbowan** [comment]
@spirosoik  no,I just pull from github

**Comment by nanbowan** [comment]
@spirosoik  when remoe the @RxLogSubscriber and @RxLogObservable ,it works.Thanks

**Comment by spirosoik** [comment]
as @android10 mentioned, this is solved here:
afd1481

I think you hadn't pull the latest  changes.

**Comment by android10** [comment]
@nanbowan I'm not having any problems after the fix. Confirm is the fix is working for you.

**Comment by ervinb** [comment]
@android10 I had to remove Frodo's annotations entirely to get the app working after cloning the repo.

**Comment by android10** [comment]
@ervinb can you post the stack trace?
And also the steps to reproduce or how you are building the app.

**Comment by ervinb** [comment]
@android10 Sure! I've cloned the project and imported it to Android Stuidio ("Import project" form the startup screen). Here's the stack trace:

```
Process: com.fernanependocejas.android10.sample.presentation, PID: 3409
java.lang.RuntimeException: Unable to start activity ComponentInfo{com.fernanependocejas.android10.sample.presentation/com.fernandocejas.android10.sample.presentation.view.activity.UserListActivity}: java.lang.NullPointerException
  at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2212)
  at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2271)
  at android.app.ActivityThread.access$800(ActivityThread.java:144)
  at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1205)
  at android.os.Handler.dispatchMessage(Handler.java:102)
  at android.os.Looper.loop(Looper.java:136)
  at android.app.ActivityThread.main(ActivityThread.java:5146)
  at java.lang.reflect.Method.invokeNative(Native Method)
  at java.lang.reflect.Method.invoke(Method.java:515)
  at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:732)
  at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:566)
at dalvik.system.NativeStart.main(Native Method)
  Caused by: java.lang.NullPointerException
  at com.fernandocejas.frodo.aspect.LogObservable.methodAnnotatedWithRxLogObservable(LogObservable.java:27)
  at com.fernandocejas.android10.sample.data.net.RestApiImpl.userEntityList(RestApiImpl.java)
  at com.fernandocejas.android10.sample.data.repository.datasource.CloudUserDataStore.userEntityList(CloudUserDataStore.java:51)
  at com.fernandocejas.android10.sample.data.repository.UserDataRepository.users(UserDataRepository.java:54)
  at com.fernandocejas.android10.sample.domain.interactor.GetUserList.buildUseCaseObservable(GetUserList.java:41)
  at com.fernandocejas.android10.sample.domain.interactor.UseCase.execute(UseCase.java:60)
  at com.fernandocejas.android10.sample.presentation.presenter.UserListPresenter.getUserList(UserListPresenter.java:115)
  at com.fernandocejas.android10.sample.presentation.presenter.UserListPresenter.loadUserList(UserListPresenter.java:79)
  at com.fernandocejas.android10.sample.presentation.presenter.UserListPresenter.initialize(UserListPresenter.java:70)
  at com.fernandocejas.android10.sample.presentation.view.fragment.UserListFragment.loadUserList(UserListFragment.java:158)
  at com.fernandocejas.android10.sample.presentation.view.fragment.UserListFragment.onViewCreated(UserListFragment.java:80)
  at android.app.FragmentManagerImpl.moveToState(FragmentManager.java:904)
  at android.app.FragmentManagerImpl.moveToState(FragmentManager.java:1062)
  at android.app.BackStackRecord.run(BackStackRecord.java:684)
  at android.app.FragmentManagerImpl.execPendingActions(FragmentManager.java:1447)
  at android.app.Activity.performStart(Activity.java:5240)
at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2178)
  at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2271) 
  at android.app.ActivityThread.access$800(ActivityThread.java:144) 
  at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1205) 
  at android.os.Handler.dispatchMessage(Handler.java:102) 
  at android.os.Looper.loop(Looper.java:136) 
  at android.app.ActivityThread.main(ActivityThread.java:5146) 
  at java.lang.reflect.Method.invokeNative(Native Method) 
  at java.lang.reflect.Method.invoke(Method.java:515) 
  at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:732) 
  at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:566) 
  at dalvik.system.NativeStart.main(Native Method)
```

**Comment by android10** [comment]
@ervinb I downgraded frodo in order to avoid NPE. 
Here is the commit: https://github.com/android10/Android-CleanArchitecture/commit/1f7a436a29f8b7133f7dea4256e8e62216ceb678

Can you make sure this issue is solved? I could not really reproduce it.
